# -*- coding: utf-8 -*-
"""Colab 시작하기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

"""
DDIM sampling + Ant environment rollout.

Vanilla DP, Periodic Phase, Phase Trajectory 모두 동일한 sampling 함수 사용 —
training과 마찬가지로 cond_fn 패턴으로 conditioning 추출 분리.
"""

import numpy as np
import torch
from typing import Callable, Optional


# =====================================================================
# Conditioning extractors at sampling time
# =====================================================================

def vanilla_sample_cond_fn(obs_window: torch.Tensor, phase_chunk=None, device='cuda'):
    """Vanilla DP: global_cond = flattened obs window. phase는 무시."""
    obs_window = obs_window.to(device)
    global_cond = obs_window.flatten(start_dim=1)
    return global_cond, None


def periodic_phase_sample_cond_fn(obs_window: torch.Tensor, phase_chunk: torch.Tensor,
                                   device='cuda'):
    """Step 3: global_cond = [flattened obs, (cosφ_0, sinφ_0)].

    phase_chunk: (B, PH) — chunk 첫 step의 phase만 사용.
    """
    obs_window = obs_window.to(device)
    phase_chunk = phase_chunk.to(device)
    phi0 = phase_chunk[:, 0:1]
    phase_enc = torch.cat([torch.cos(phi0), torch.sin(phi0)], dim=-1)
    global_cond = torch.cat([obs_window.flatten(start_dim=1), phase_enc], dim=-1)
    return global_cond, None


# =====================================================================
# DDIM sampling
# =====================================================================

@torch.no_grad()
def sample_action_chunk(
    model,
    ema,
    noise_scheduler_config: dict,
    obs_window: torch.Tensor,
    phase_chunk: Optional[torch.Tensor] = None,
    cond_fn: Callable = vanilla_sample_cond_fn,
    pred_horizon: int = 16,
    act_dim: int = 8,
    num_inference_steps: int = 16,
    use_ema: bool = True,
    device: str = 'cuda',
    seed: Optional[int] = None,
) -> torch.Tensor:
    """DDIM sampling. EMA weights를 inference에 사용 (DP 표준).

    seed: torch.manual_seed 적용. 재현성 필요 시 사용 (paper evaluation).
    """
    from diffusers.schedulers.scheduling_ddim import DDIMScheduler

    if seed is not None:
        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    if use_ema:
        ema.store(model.parameters())
        ema.copy_to(model.parameters())
    model.eval()

    # Batch 차원 처리
    if obs_window.dim() == 2:
        obs_window = obs_window.unsqueeze(0)
    if phase_chunk is not None and phase_chunk.dim() == 1:
        phase_chunk = phase_chunk.unsqueeze(0)
    obs_window = obs_window.to(device)
    B = obs_window.shape[0]

    global_cond, per_step_cond = cond_fn(obs_window, phase_chunk, device=device)

    sched = DDIMScheduler(
        num_train_timesteps=noise_scheduler_config['num_train_timesteps'],
        beta_schedule=noise_scheduler_config['beta_schedule'],
        prediction_type=noise_scheduler_config['prediction_type'],
        clip_sample=noise_scheduler_config['clip_sample'],
    )
    sched.set_timesteps(num_inference_steps)

    x = torch.randn(B, pred_horizon, act_dim, device=device)

    for t in sched.timesteps:
        if per_step_cond is None:
            noise_pred = model(x, t, global_cond)
        else:
            noise_pred = model(x, t, global_cond, per_step_cond)
        x = sched.step(noise_pred, t, x).prev_sample

    if use_ema:
        ema.restore(model.parameters())

    return x.cpu()


# =====================================================================
# MuJoCo Ant rollout
# =====================================================================

@torch.no_grad()
def rollout(
    model,
    ema,
    env,
    noise_scheduler_config: dict,
    obs_mean: np.ndarray,
    obs_std: np.ndarray,
    act_min: np.ndarray,
    act_range: np.ndarray,
    cond_fn: Callable = vanilla_sample_cond_fn,
    obs_horizon: int = 2,
    pred_horizon: int = 16,
    action_horizon: int = 8,
    obs_dim: int = 105,
    act_dim: int = 8,
    num_inference_steps: int = 16,
    max_steps: int = 300,
    seed: int = 0,
    render: bool = False,
    phase_trajectory_fn: Optional[Callable] = None,
    device: str = 'cuda',
    sampling_seed_base: Optional[int] = None,
) -> dict:
    """학습된 DP를 MuJoCo Ant 환경에서 rollout.

    Receding-horizon control: chunk 16 step 샘플링 → 앞 8 step 실행 → re-plan.

    phase_trajectory_fn: Step 3+에서 사용. (current_t_global, pred_horizon) → (PH,) phase array.
        None이면 Vanilla DP.
    """
    # EMA weights 적용
    ema.store(model.parameters())
    ema.copy_to(model.parameters())
    model.eval()

    obs, _ = env.reset(seed=seed)
    obs = obs[:obs_dim]
    obs_history = [obs.copy() for _ in range(obs_horizon)]   # 초기엔 같은 obs 반복

    total_reward = 0.0
    survival = 0
    obs_log, act_log, frames = [], [], []

    step = 0
    while step < max_steps:
        # Obs window 정규화
        obs_arr = np.stack(obs_history[-obs_horizon:])         # (OH, OD)
        obs_n = (obs_arr - obs_mean) / obs_std
        obs_tensor = torch.from_numpy(obs_n).float()

        # Phase trajectory (Step 3+에서 사용)
        phase_chunk = None
        if phase_trajectory_fn is not None:
            phase_arr = phase_trajectory_fn(step, pred_horizon)  # (PH,)
            phase_chunk = torch.from_numpy(phase_arr.astype(np.float32))

        # Sample chunk (use_ema=False → 위에서 이미 EMA 적용 중이라 중복 방지)
        # Sampling seed: 매 chunk마다 deterministic + 다른 값 (rollout 내 다양성 유지)
        chunk_seed = None
        if sampling_seed_base is not None:
            chunk_seed = sampling_seed_base * 100000 + step
        
        chunk_n = sample_action_chunk(
            model, ema, noise_scheduler_config,
            obs_tensor, phase_chunk=phase_chunk,
            cond_fn=cond_fn,
            pred_horizon=pred_horizon, act_dim=act_dim,
            num_inference_steps=num_inference_steps,
            use_ema=False, device=device,
            seed=chunk_seed,                     # ← 추가
        ).numpy()[0]

        # Unnormalize
        chunk = (chunk_n + 1.0) / 2.0 * act_range + act_min
        low, high = env.action_space.low, env.action_space.high
        chunk = np.clip(chunk, low, high)

        # Execute action_horizon steps
        for k in range(min(action_horizon, max_steps - step)):
            action = chunk[k]
            obs_next, reward, terminated, truncated, _ = env.step(action)
            total_reward += reward
            survival += 1
            step += 1

            obs_next_t = obs_next[:obs_dim]
            obs_history.append(obs_next_t)
            obs_log.append(obs_next_t)
            act_log.append(action)

            if render:
                frames.append(env.render())
            if terminated or truncated:
                break
        if terminated or truncated:
            break

    ema.restore(model.parameters())

    return {
        'total_reward': float(total_reward),
        'survival':     int(survival),
        'obs_log':      np.asarray(obs_log),
        'act_log':      np.asarray(act_log),
        'frames':       frames,
    }


def rollout_multi_seed(model, ema, env, n_seeds: int = 5, deterministic_sampling: bool = True, **kwargs) -> list:
    """여러 seed로 rollout. 통계용 (mean ± std).
    deterministic_sampling=True: 각 rollout의 sampling이 환경 seed에 deterministic.
    Paper evaluation에 권장."""
    results = []
    for s in range(n_seeds):
        sampling_seed_base = s if deterministic_sampling else None
        res = rollout(model, ema, env, seed=s, sampling_seed_base=sampling_seed_base, **kwargs)
        results.append(res)
        print(f"  seed {s}: survival={res['survival']:>3d} steps, "
              f"total_reward={res['total_reward']:>8.1f}")

    surv = np.array([r['survival'] for r in results])
    rew  = np.array([r['total_reward'] for r in results])
    print(f"\nSurvival:  mean={surv.mean():.0f} ± {surv.std():.0f} steps")
    print(f"Reward:    mean={rew.mean():.1f} ± {rew.std():.1f}")

    return results


# =====================================================================
# Diagnostics
# =====================================================================

def diagnose_obs_distribution(rollout_results, obs_mean, obs_std, obs_dim: int):
    """Rollout 중 관측된 obs를 정규화한 후 학습 분포와 비교.

    Obs format mismatch (Plan C 105차원 vs Ant-v5 환경) 진단용.
    """
    if rollout_results[0]['survival'] == 0:
        print("Rollout 0 step. 환경 자체 문제.")
        return None

    rollout_obs = np.concatenate([r['obs_log'] for r in rollout_results], axis=0)
    rollout_obs_n = (rollout_obs - obs_mean) / obs_std

    print(f"=== Rollout obs (정규화 후) 분포 ===")
    print(f"전체 mean: {rollout_obs_n.mean():.3f} (학습 분포: ~0)")
    print(f"전체 std:  {rollout_obs_n.std():.3f} (학습 분포: ~1)")
    print(f"|값| > 5 비율: {(np.abs(rollout_obs_n) > 5).mean()*100:.1f}% "
          f"(학습 분포: <0.5%; 클수록 mismatch)")

    dim_means = rollout_obs_n.mean(axis=0)
    print(f"\n차원별 mean (학습 분포 ~0):")
    print(f"  abs(mean) > 1 차원 수: {(np.abs(dim_means) > 1).sum()}/{obs_dim}")
    print(f"  abs(mean) > 3 차원 수: {(np.abs(dim_means) > 3).sum()}/{obs_dim}")

    worst_dims = np.argsort(np.abs(dim_means))[::-1][:5]
    print(f"\nTop 5 mismatch 차원:")
    for d in worst_dims:
        print(f"  dim {d}: {dim_means[d]:+.3f}")

    return {
        'rollout_obs_n': rollout_obs_n,
        'dim_means':     dim_means,
        'worst_dims':    worst_dims,
    }


# ====================================================================
def trajectory_phase_sample_cond_fn(obs_window: torch.Tensor,
                                     phase_chunk: torch.Tensor,
                                     device: str = 'cuda'):
    """Step 4 sampling: per-step phase trajectory.

    phase_chunk: (B, PH) — full chunk phase trajectory.
    Returns (global_cond, per_step_cond) where per_step_cond is (B, PH, 2).
    """
    obs_window = obs_window.to(device)
    phase_chunk = phase_chunk.to(device)

    global_cond = obs_window.flatten(start_dim=1)
    per_step_cond = torch.stack([
        torch.cos(phase_chunk),
        torch.sin(phase_chunk),
    ], dim=-1)
    return global_cond, per_step_cond

#===========================================================================
# =====================================================================
# Step 5: DDIM sampling with phase consistency guidance
# =====================================================================

def sample_action_chunk_with_guidance(
    model,
    ema,
    noise_scheduler_config: dict,
    obs_window: torch.Tensor,
    phase_chunk: torch.Tensor,
    cond_fn,
    pred_horizon: int = 16,
    act_dim: int = 8,
    num_inference_steps: int = 16,
    guidance_scale: float = 0.0,
    diff_norm_per_phase: float = 1.0,
    use_ema: bool = True,
    device: str = 'cuda',
) -> torch.Tensor:
    """DDIM sampling with phase consistency cost gradient injection."""
    from diffusers.schedulers.scheduling_ddim import DDIMScheduler

    if use_ema:
        ema.store(model.parameters())
        ema.copy_to(model.parameters())
    model.eval()

    if obs_window.dim() == 2:
        obs_window = obs_window.unsqueeze(0)
    if phase_chunk.dim() == 1:
        phase_chunk = phase_chunk.unsqueeze(0)
    obs_window  = obs_window.to(device)
    phase_chunk = phase_chunk.to(device)
    B = obs_window.shape[0]

    # === IMPORTANT: vanilla sample_action_chunk 와 동일 순서 유지 ===
    # 1. cond_fn 호출
    global_cond, per_step_cond = cond_fn(obs_window, phase_chunk, device=device)

    # 2. DDIM scheduler 생성
    sched = DDIMScheduler(
        num_train_timesteps=noise_scheduler_config['num_train_timesteps'],
        beta_schedule=noise_scheduler_config['beta_schedule'],
        prediction_type=noise_scheduler_config['prediction_type'],
        clip_sample=noise_scheduler_config['clip_sample'],
    )
    sched.set_timesteps(num_inference_steps)

    # 3. randn — vanilla와 정확히 같은 시점
    x = torch.randn(B, pred_horizon, act_dim, device=device)

    # 4. Guidance 셋업 (randn 이후에 — RNG state 영향 없음)
    alphas_cumprod = sched.alphas_cumprod.to(device)
    if guidance_scale > 0:
        # Phase diff 계산 (guidance 사용 시에만)
        phi_unwrap = torch.cumsum(
            torch.cat([phase_chunk[:, :1], _phase_step_diff(phase_chunk)], dim=1), dim=1
        )
        phase_diff = (phi_unwrap[:, 1:] - phi_unwrap[:, :-1]).abs()  # (B, PH-1)

        # K table or scalar 처리
        if isinstance(diff_norm_per_phase, (int, float)):
            expected_norm = float(diff_norm_per_phase) * phase_diff
        else:
            K_table = torch.as_tensor(diff_norm_per_phase, dtype=torch.float32, device=device)
            n_bins = K_table.shape[0]
            ph_start = phase_chunk[:, :-1] % (2 * torch.pi)
            bin_idx = (ph_start / (2 * torch.pi) * n_bins).long().clamp(0, n_bins - 1)
            K_per_step = K_table[bin_idx]
            expected_norm = K_per_step * phase_diff

    # 5. Sampling loop (vanilla와 동일 구조, gs=0이면 vanilla와 동일 동작)
    for t in sched.timesteps:
        if guidance_scale > 0:
            x_in = x.detach().requires_grad_(True)
            with torch.enable_grad():
                if per_step_cond is None:
                    noise_pred = model(x_in, t, global_cond)
                else:
                    noise_pred = model(x_in, t, global_cond, per_step_cond)

                alpha_t = alphas_cumprod[t]
                x_hat_0 = (x_in - (1 - alpha_t).sqrt() * noise_pred) / alpha_t.sqrt()

                action_diff = x_hat_0[:, 1:, :] - x_hat_0[:, :-1, :]
                action_diff_norm = action_diff.norm(dim=-1)
                cost = ((action_diff_norm - expected_norm) ** 2).mean()

                grad = torch.autograd.grad(cost, x_in)[0]

            lambda_t = guidance_scale * (alpha_t / (1 - alpha_t + 1e-8)).sqrt()
            x = x_in.detach() - lambda_t * grad.detach()
            noise_pred = noise_pred.detach()
        else:
            with torch.no_grad():
                if per_step_cond is None:
                    noise_pred = model(x, t, global_cond)
                else:
                    noise_pred = model(x, t, global_cond, per_step_cond)

        x = sched.step(noise_pred, t, x).prev_sample

    if use_ema:
        ema.restore(model.parameters())

    return x.cpu()


def _phase_step_diff(phase: torch.Tensor) -> torch.Tensor:
    """Phase wraparound을 처리한 step별 diff. Returns (B, T-1) of *signed* diffs.

    Phase가 [0, 2π)로 들어오면 cycle 경계에서 큰 음수 jump가 생김.
    그걸 +2π 보정해서 monotonic diff로 만듦 (forward 보행 가정).
    """
    raw = phase[:, 1:] - phase[:, :-1]        # (B, T-1)
    # 큰 음수 (>π) jump를 +2π로 보정
    raw = torch.where(raw < -torch.pi, raw + 2 * torch.pi, raw)
    return raw